apiVersion: apps/v1
kind: Deployment
metadata:
  name: signup-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: signup-app
  template:
    metadata:
      labels:
        app: signup-app
    spec:
      containers:
      - name: signup-app
        image: gcr.io/alert-flames-286515/signup-python-app:latest
        ports:
        - containerPort: 8080
